kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v2alpha1
mirror:
  platform:
    channels:
    - name: stable-4.19
      minVersion: 4.19.10
      maxVersion: 4.19.15
    graph: true
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.19
      packages:
       - name: kubernetes-nmstate-operator
         channels:
         - name: stable
       - name: kubevirt-hyperconverged
         channels:
         - name: stable
       - name: compliance-operator
         channels:
         - name: stable
       - name: cluster-logging
         channels:
         - name: stable-6.3
       - name: loki-operator
         channels:
         - name: stable-6.3
       - name: metallb-operator
         channels:
         - name: stable
       - name: cluster-observability-operator
         channels:
         - name: stable
       - name: cluster-kube-descheduler-operator
         channels:
         - name: stable
       - name: netobserv-operator
         channels:
         - name: stable
       - name: local-storage-operator
       - name: mtv-operator
         channels:
         - name: release-v2.9
       - name: redhat-oadp-operator
         channels:
         - name: stable
       - name: fence-agents-remediation
         channels:
         - name: stable
       - name: node-healthcheck-operator
         channels:
         - name: stable
       - name: node-maintenance-operator
         channels:
         - name: stable
       - name: advanced-cluster-management
         channels:
         - name: release-2.14
       - name: self-node-remediation
         channels:
         - name: stable
       - name: odf-csi-addons-operator
         channels:
         - name: stable-4.19
       - name: odf-dependencies
         channels:
         - name: stable-4.19
       - name: odf-multicluster-orchestrator
         channels:
         - name: stable-4.19
       - name: odf-prometheus-operator
         channels:
         - name: stable-4.19
       - name: local-storage-operator
         channels:
         - name: stable
       - name: ocs-operator
         channels:
         - name: stable-4.19
       - name: ocs-client-operator
         channels:
         - name: stable-4.19
       - name: mcg-operator
         channels:
         - name: stable-4.19
       - name: recipe
         channels:
         - name: stable-4.19
       - name: rook-ceph-operator
         channels:
         - name: stable-4.19
       - name: ceph-csi-operator
         channels:
         - name: stable-4.19
       - name: odr-cluster-operator
         channels:
         - name: stable-4.19
       - name: odr-hub-operator
         channels:
         - name: stable-4.19
       - name: multicluster-engine
         channels:
         - name: stable-2.9
       - name: servicemeshoperator3
         channels:
         - name: stable-3.1
       - name: kiali-ossm
         channels:
         - name: stable
       - name: openshift-gitops-operator
         channels:
         - name: latest
       - name: cluster-observability-operator
         channels:
         - name: stable
       - name: tempo-product
         channels:
         - name: stable
  
  additionalImages:
    - name: registry.redhat.io/ubi8/ubi:latest
    - name: registry.redhat.io/rhel8/support-tools
    - name: docker.io/netapp/trident:25.10.0
    - name: docker.io/netapp/trident-autosupport:25.10.0
    